apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  ref:
    branch: main
  secretRef:
    name: basic-access-github
  interval: 1m
  url: https://github.com/MovieMaker93/homelab
