apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallabag
resources:
  - networking.yaml
  - deployment.yaml
  - namespace.yaml
  - ./secret-wallabag-db.yaml
  - ./secret-wallabag-postgres.yaml
  - ./secret-storage.yaml
  - ./wallabag-superuser.yaml
