apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-storage-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: azure-creds
    creationPolicy: Owner
    # template:
    #   type: kubernetes.io/basic-auth
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    # - secretKey: wallabag-storage-account-name
    #   remoteRef:
    #     key: wallabag-storage-account
    # - secretKey: wallabag-blob-sas
    #   remoteRef:
    #     key: wallabag-blob-sas
    - secretKey: wallabag-connection-string
      remoteRef:
        key: wallabag-connection-string
