apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-db-creds-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: wallabag-container-env
    creationPolicy: Owner
    # template:
    #   type: kubernetes.io/basic-auth
    #   metadata:
    #     annotations: {}
    #     labels: {}
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: SYMFONY__ENV__DATABASE_PASSWORD
      remoteRef:
        key: wallabag-symphony-password
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: wallabag-symphony-password
