apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wallabag-db-creds-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: wallabag-db-creds
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: username
      remoteRef:
        key: wallabag-db-username
    - secretKey: password
      remoteRef:
        key: wallabag-symphony-password
