apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secret-operator
nameSuffix: "-dev"
resources:
  - ../../base/external-secret-operator
  - secret-sp.yaml
patches:
  - target:
      kind: ClusterSecretStore
    patch: |-
      - op: replace
        path: /spec/provider/azurekv/vaultUrl
        value: "https://homelab-dev-alfonso.vault.azure.net"
      - op: replace
        path:  /spec/provider/azurekv/authSecretRef/clientId/name
        value: azure-secret-sp-dev
      - op: replace
        path:  /spec/provider/azurekv/authSecretRef/clientSecret/name
        value: azure-secret-sp-dev
