apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallabeg
resources:
  - ../../base/wallabeg
  - ./configmap.yaml
  - ./database.yaml
  # - ./ingress.yaml
  - ./schedule-backup.yaml
  - ./cloudflared.yaml
  - ./tunnel-secret.yaml
