apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: "7.3.9"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    # configuration to make dashboard configmaps discoverable
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        # Allow discovery in all namespaces for dashboards
        searchNamespace: ALL
        provider:
          allowUiUpdates: true
    persistence:
      enabled: true
      type: pvc
      accessModes:
        - ReadWriteOnce
      size: 4Gi
