apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Gandalf Dev Cluster Homepage
    theme: dark
    color: slate
    layout:
      Monitoring:
        header: true
        style: row
        columns: 4
      Apps:
        header: true
        style: row
        columns: 4
    background:
      image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
      blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
      saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
      brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 100 # 0-100 # providers:
  #   longhorn:
  #     url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Skool Kubecraft:
        - Skool:
            - abbr: sk
              href: https://www.skool.com/kubecraft
    - Personal Blog:
        - Blog:
            - abbr: bl
              href: https://alfonsofortunato.com
              icon: si-devpost-#003E54
    - Socials:
        - Github:
            - abbr: GH
              href: https://github.com/MovieMaker93
              icon: github-light.png
        - Linkedin:
            - abbr: LN
              href: https://www.linkedin.com/in/alfonso-fortunato-a37056b9/
              icon: linkedin.png
        - Twitter:
            - abbr: X
              href: https://x.com/devopsfortunato
              icon: mdi-twitter
        - Medium:
            - abbr: M
              href: https://medium.com/@alfor93
              icon: si-medium-#000000
        - Reddit:
            - abbr: M
              href: https://reddit.com/
              icon: reddit.png
  services.yaml: |
    - Apps:
        - Wallabag:
            href: https://wallabag.alfonsofortunato.net/
            description: Wallabag
            icon: si-wallabag-#3F6184
        - Commafeed:
            href: https://commafeed.alfonsofortunato.net/
            description: Commafeed
            icon: commafeed.png
        - Linkding:
            href: https://linkding.alfonsofortunato.net/
            description: Linkding
            icon: linkding.png
        - Excalidraw:
            href: https://excalidraw.alfonsofortunato.net/
            description: Excalidraw
            icon: excalidraw-light.png
    - Monitoring:
        - Grafana:
            href: https://grafana-dev.alfonsofortunato.net/
            description: Grafana dashboard
            icon: grafana.png
            widget:
              type: grafana
              url: https://grafana-dev.alfonsofortunato.net
              username: admin
              password: strongpassword
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - datetime:
        text_size: xl
        format:
          timeStyle: short
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
