apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: ScheduledBackup
metadata:
  name: linkding-db-schedule
  namespace: linkding
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: linkding-db-dev-v1
