apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-secret-linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: tunnel-credentials
    creationPolicy: Owner
    # template:
    #   type: kubernetes.io/basic-auth
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: credentials.json
      remoteRef:
        key: linkding-tunnel-cred
