apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secret-release
  namespace: external-secret-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.10.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secret-operator
      interval: 12h
