apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallabag
resources:
  - networking.yaml
  - deployment.yaml
  - namespace.yaml
  - storage.yaml
  - ./secret-linkding-db.yaml
  - ./secret-storage.yaml
  - ./secret-linkding-postgres.yaml
