apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-db-creds-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: linkding-container-env
    creationPolicy: Owner
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: linkding-superuser-name
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: linkding-superuser-password
    - secretKey: LD_DB_USER
      remoteRef:
        key: linkding-db-username
    - secretKey: LD_DB_PASSWORD
      remoteRef:
        key: linkding-db-password
  # - secretKey: LD_DB_HOST
  #   remoteRef:
  #     key: linkding-db-host
