apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-storage-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: azure-creds
    creationPolicy: Owner
  data:
    - secretKey: linkding-connection-string
      remoteRef:
        key: linkding-connection-string
