apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: commafeed
resources:
  - network.yaml
  - deployment.yaml
  - ./secret-commafeed-db-creds.yaml
  - ./secret-commafeed-container-env.yaml
  - ./secret-storage-creds.yaml
  - namespace.yaml
