apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: commafeed-storage-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: azure-creds
    creationPolicy: Owner
    # template:
    #   type: kubernetes.io/basic-auth
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: commafeed-storage-account-name
      remoteRef:
        key: commafeed-storage-account
    - secretKey: commafeed-blob-sas
      remoteRef:
        key: commafeed-blob-sas
    - secretKey: commafeed-connection-string
      remoteRef:
        key: commafeed-connection-string
