apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: commafeed-db-creds-postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secret-store-dev
  target:
    name: commafeed-container-env
    creationPolicy: Owner
    # template:
    #   type: kubernetes.io/basic-auth
    #   metadata:
    #     annotations: {}
    #     labels: {}
  data:
    # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
    - secretKey: CF_DATABASE_USER
      remoteRef:
        key: commafeed-db-username
    - secretKey: CF_DATABASE_PASSWORD
      remoteRef:
        key: commafeed-db-password
